package com.zdd.risk.bean;

import java.util.Date;

public class Accredit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_accredit.id
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_accredit.orderId
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_accredit.userId
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_accredit.accreditInfo
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    private String accreditinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_accredit.createTime
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_accredit.id
     *
     * @return the value of risk_accredit.id
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_accredit.id
     *
     * @param id the value for risk_accredit.id
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_accredit.orderId
     *
     * @return the value of risk_accredit.orderId
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_accredit.orderId
     *
     * @param orderid the value for risk_accredit.orderId
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_accredit.userId
     *
     * @return the value of risk_accredit.userId
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_accredit.userId
     *
     * @param userid the value for risk_accredit.userId
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_accredit.accreditInfo
     *
     * @return the value of risk_accredit.accreditInfo
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public String getAccreditinfo() {
        return accreditinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_accredit.accreditInfo
     *
     * @param accreditinfo the value for risk_accredit.accreditInfo
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public void setAccreditinfo(String accreditinfo) {
        this.accreditinfo = accreditinfo == null ? null : accreditinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_accredit.createTime
     *
     * @return the value of risk_accredit.createTime
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_accredit.createTime
     *
     * @param createtime the value for risk_accredit.createTime
     *
     * @mbg.generated Tue Nov 06 15:02:16 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}