package com.zdd.risk.bean;

import java.util.Date;

public class ApplyAmount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.id
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.userId
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyAmount
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private Integer applyamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyDays
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private String applydays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyMonths
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private String applymonths;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.contractAmount
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private Integer contractamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.createTime
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.id
     *
     * @return the value of risk_applyAmount.id
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.id
     *
     * @param id the value for risk_applyAmount.id
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.userId
     *
     * @return the value of risk_applyAmount.userId
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.userId
     *
     * @param userid the value for risk_applyAmount.userId
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyAmount
     *
     * @return the value of risk_applyAmount.applyAmount
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public Integer getApplyamount() {
        return applyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyAmount
     *
     * @param applyamount the value for risk_applyAmount.applyAmount
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setApplyamount(Integer applyamount) {
        this.applyamount = applyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyDays
     *
     * @return the value of risk_applyAmount.applyDays
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public String getApplydays() {
        return applydays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyDays
     *
     * @param applydays the value for risk_applyAmount.applyDays
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setApplydays(String applydays) {
        this.applydays = applydays == null ? null : applydays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyMonths
     *
     * @return the value of risk_applyAmount.applyMonths
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public String getApplymonths() {
        return applymonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyMonths
     *
     * @param applymonths the value for risk_applyAmount.applyMonths
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setApplymonths(String applymonths) {
        this.applymonths = applymonths == null ? null : applymonths.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.contractAmount
     *
     * @return the value of risk_applyAmount.contractAmount
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public Integer getContractamount() {
        return contractamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.contractAmount
     *
     * @param contractamount the value for risk_applyAmount.contractAmount
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setContractamount(Integer contractamount) {
        this.contractamount = contractamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.createTime
     *
     * @return the value of risk_applyAmount.createTime
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.createTime
     *
     * @param createtime the value for risk_applyAmount.createTime
     *
     * @mbg.generated Tue Nov 06 15:01:52 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}