package com.zdd.risk.bean;

import java.util.Date;

public class ApplyAmount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.id
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.bizno
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private String bizno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.userId
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.modelNo
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private Integer modelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private Integer applyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyDays
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private String applyDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyMonths
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private String applyMonths;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.contractAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private Integer contractAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.createTime
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.applyId
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.updateTime
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_applyAmount.bankName
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    private String bankName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.id
     *
     * @return the value of risk_applyAmount.id
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.id
     *
     * @param id the value for risk_applyAmount.id
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.bizno
     *
     * @return the value of risk_applyAmount.bizno
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getBizno() {
        return bizno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.bizno
     *
     * @param bizno the value for risk_applyAmount.bizno
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setBizno(String bizno) {
        this.bizno = bizno == null ? null : bizno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.userId
     *
     * @return the value of risk_applyAmount.userId
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.userId
     *
     * @param userId the value for risk_applyAmount.userId
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.modelNo
     *
     * @return the value of risk_applyAmount.modelNo
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Integer getModelNo() {
        return modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.modelNo
     *
     * @param modelNo the value for risk_applyAmount.modelNo
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setModelNo(Integer modelNo) {
        this.modelNo = modelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyAmount
     *
     * @return the value of risk_applyAmount.applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Integer getApplyAmount() {
        return applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyAmount
     *
     * @param applyAmount the value for risk_applyAmount.applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setApplyAmount(Integer applyAmount) {
        this.applyAmount = applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyDays
     *
     * @return the value of risk_applyAmount.applyDays
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getApplyDays() {
        return applyDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyDays
     *
     * @param applyDays the value for risk_applyAmount.applyDays
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setApplyDays(String applyDays) {
        this.applyDays = applyDays == null ? null : applyDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyMonths
     *
     * @return the value of risk_applyAmount.applyMonths
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getApplyMonths() {
        return applyMonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyMonths
     *
     * @param applyMonths the value for risk_applyAmount.applyMonths
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setApplyMonths(String applyMonths) {
        this.applyMonths = applyMonths == null ? null : applyMonths.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.contractAmount
     *
     * @return the value of risk_applyAmount.contractAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Integer getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.contractAmount
     *
     * @param contractAmount the value for risk_applyAmount.contractAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setContractAmount(Integer contractAmount) {
        this.contractAmount = contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.createTime
     *
     * @return the value of risk_applyAmount.createTime
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.createTime
     *
     * @param createTime the value for risk_applyAmount.createTime
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.applyId
     *
     * @return the value of risk_applyAmount.applyId
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.applyId
     *
     * @param applyId the value for risk_applyAmount.applyId
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.updateTime
     *
     * @return the value of risk_applyAmount.updateTime
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.updateTime
     *
     * @param updateTime the value for risk_applyAmount.updateTime
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_applyAmount.bankName
     *
     * @return the value of risk_applyAmount.bankName
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_applyAmount.bankName
     *
     * @param bankName the value for risk_applyAmount.bankName
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }
}