package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplyAmountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public ApplyAmountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBiznoIsNull() {
            addCriterion("`bizno` is null");
            return (Criteria) this;
        }

        public Criteria andBiznoIsNotNull() {
            addCriterion("`bizno` is not null");
            return (Criteria) this;
        }

        public Criteria andBiznoEqualTo(String value) {
            addCriterion("`bizno` =", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotEqualTo(String value) {
            addCriterion("`bizno` <>", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoGreaterThan(String value) {
            addCriterion("`bizno` >", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoGreaterThanOrEqualTo(String value) {
            addCriterion("`bizno` >=", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLessThan(String value) {
            addCriterion("`bizno` <", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLessThanOrEqualTo(String value) {
            addCriterion("`bizno` <=", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLike(String value) {
            addCriterion("`bizno` like", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotLike(String value) {
            addCriterion("`bizno` not like", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoIn(List<String> values) {
            addCriterion("`bizno` in", values, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotIn(List<String> values) {
            addCriterion("`bizno` not in", values, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoBetween(String value1, String value2) {
            addCriterion("`bizno` between", value1, value2, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotBetween(String value1, String value2) {
            addCriterion("`bizno` not between", value1, value2, "bizno");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("`userId` is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("`userId` is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("`userId` =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("`userId` <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("`userId` >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`userId` >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("`userId` <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("`userId` <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("`userId` like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("`userId` not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("`userId` in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("`userId` not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("`userId` between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("`userId` not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andModelNoIsNull() {
            addCriterion("`modelNo` is null");
            return (Criteria) this;
        }

        public Criteria andModelNoIsNotNull() {
            addCriterion("`modelNo` is not null");
            return (Criteria) this;
        }

        public Criteria andModelNoEqualTo(Integer value) {
            addCriterion("`modelNo` =", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotEqualTo(Integer value) {
            addCriterion("`modelNo` <>", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoGreaterThan(Integer value) {
            addCriterion("`modelNo` >", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("`modelNo` >=", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLessThan(Integer value) {
            addCriterion("`modelNo` <", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoLessThanOrEqualTo(Integer value) {
            addCriterion("`modelNo` <=", value, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoIn(List<Integer> values) {
            addCriterion("`modelNo` in", values, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotIn(List<Integer> values) {
            addCriterion("`modelNo` not in", values, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoBetween(Integer value1, Integer value2) {
            addCriterion("`modelNo` between", value1, value2, "modelNo");
            return (Criteria) this;
        }

        public Criteria andModelNoNotBetween(Integer value1, Integer value2) {
            addCriterion("`modelNo` not between", value1, value2, "modelNo");
            return (Criteria) this;
        }

        public Criteria andApplyAmountIsNull() {
            addCriterion("`applyAmount` is null");
            return (Criteria) this;
        }

        public Criteria andApplyAmountIsNotNull() {
            addCriterion("`applyAmount` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyAmountEqualTo(Integer value) {
            addCriterion("`applyAmount` =", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountNotEqualTo(Integer value) {
            addCriterion("`applyAmount` <>", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountGreaterThan(Integer value) {
            addCriterion("`applyAmount` >", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`applyAmount` >=", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountLessThan(Integer value) {
            addCriterion("`applyAmount` <", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountLessThanOrEqualTo(Integer value) {
            addCriterion("`applyAmount` <=", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountIn(List<Integer> values) {
            addCriterion("`applyAmount` in", values, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountNotIn(List<Integer> values) {
            addCriterion("`applyAmount` not in", values, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountBetween(Integer value1, Integer value2) {
            addCriterion("`applyAmount` between", value1, value2, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("`applyAmount` not between", value1, value2, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyDaysIsNull() {
            addCriterion("`applyDays` is null");
            return (Criteria) this;
        }

        public Criteria andApplyDaysIsNotNull() {
            addCriterion("`applyDays` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDaysEqualTo(String value) {
            addCriterion("`applyDays` =", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysNotEqualTo(String value) {
            addCriterion("`applyDays` <>", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysGreaterThan(String value) {
            addCriterion("`applyDays` >", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysGreaterThanOrEqualTo(String value) {
            addCriterion("`applyDays` >=", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysLessThan(String value) {
            addCriterion("`applyDays` <", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysLessThanOrEqualTo(String value) {
            addCriterion("`applyDays` <=", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysLike(String value) {
            addCriterion("`applyDays` like", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysNotLike(String value) {
            addCriterion("`applyDays` not like", value, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysIn(List<String> values) {
            addCriterion("`applyDays` in", values, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysNotIn(List<String> values) {
            addCriterion("`applyDays` not in", values, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysBetween(String value1, String value2) {
            addCriterion("`applyDays` between", value1, value2, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyDaysNotBetween(String value1, String value2) {
            addCriterion("`applyDays` not between", value1, value2, "applyDays");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsIsNull() {
            addCriterion("`applyMonths` is null");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsIsNotNull() {
            addCriterion("`applyMonths` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsEqualTo(String value) {
            addCriterion("`applyMonths` =", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsNotEqualTo(String value) {
            addCriterion("`applyMonths` <>", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsGreaterThan(String value) {
            addCriterion("`applyMonths` >", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsGreaterThanOrEqualTo(String value) {
            addCriterion("`applyMonths` >=", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsLessThan(String value) {
            addCriterion("`applyMonths` <", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsLessThanOrEqualTo(String value) {
            addCriterion("`applyMonths` <=", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsLike(String value) {
            addCriterion("`applyMonths` like", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsNotLike(String value) {
            addCriterion("`applyMonths` not like", value, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsIn(List<String> values) {
            addCriterion("`applyMonths` in", values, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsNotIn(List<String> values) {
            addCriterion("`applyMonths` not in", values, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsBetween(String value1, String value2) {
            addCriterion("`applyMonths` between", value1, value2, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andApplyMonthsNotBetween(String value1, String value2) {
            addCriterion("`applyMonths` not between", value1, value2, "applyMonths");
            return (Criteria) this;
        }

        public Criteria andContractAmountIsNull() {
            addCriterion("`contractAmount` is null");
            return (Criteria) this;
        }

        public Criteria andContractAmountIsNotNull() {
            addCriterion("`contractAmount` is not null");
            return (Criteria) this;
        }

        public Criteria andContractAmountEqualTo(Integer value) {
            addCriterion("`contractAmount` =", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotEqualTo(Integer value) {
            addCriterion("`contractAmount` <>", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountGreaterThan(Integer value) {
            addCriterion("`contractAmount` >", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`contractAmount` >=", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountLessThan(Integer value) {
            addCriterion("`contractAmount` <", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountLessThanOrEqualTo(Integer value) {
            addCriterion("`contractAmount` <=", value, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountIn(List<Integer> values) {
            addCriterion("`contractAmount` in", values, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotIn(List<Integer> values) {
            addCriterion("`contractAmount` not in", values, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountBetween(Integer value1, Integer value2) {
            addCriterion("`contractAmount` between", value1, value2, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andContractAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("`contractAmount` not between", value1, value2, "contractAmount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`createTime` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`createTime` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`createTime` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`createTime` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`createTime` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`createTime` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`createTime` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`createTime` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`createTime` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`createTime` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`createTime` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`createTime` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("`applyId` is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("`applyId` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(String value) {
            addCriterion("`applyId` =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(String value) {
            addCriterion("`applyId` <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(String value) {
            addCriterion("`applyId` >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("`applyId` >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(String value) {
            addCriterion("`applyId` <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(String value) {
            addCriterion("`applyId` <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLike(String value) {
            addCriterion("`applyId` like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotLike(String value) {
            addCriterion("`applyId` not like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<String> values) {
            addCriterion("`applyId` in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<String> values) {
            addCriterion("`applyId` not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(String value1, String value2) {
            addCriterion("`applyId` between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(String value1, String value2) {
            addCriterion("`applyId` not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`updateTime` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`updateTime` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`updateTime` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`updateTime` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`updateTime` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`updateTime` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`updateTime` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`updateTime` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`updateTime` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`updateTime` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`updateTime` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`updateTime` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("`bankName` is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("`bankName` is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("`bankName` =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("`bankName` <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("`bankName` >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("`bankName` >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("`bankName` <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("`bankName` <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("`bankName` like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("`bankName` not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("`bankName` in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("`bankName` not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("`bankName` between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("`bankName` not between", value1, value2, "bankName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_applyAmount
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 21 16:26:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_applyAmount
     *
     * @mbg.generated Wed Nov 21 16:26:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}