package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApproveResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public ApproveResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("`userId` is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("`userId` is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("`userId` =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("`userId` <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("`userId` >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("`userId` >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("`userId` <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("`userId` <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("`userId` like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("`userId` not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("`userId` in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("`userId` not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("`userId` between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("`userId` not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andBiznoIsNull() {
            addCriterion("`bizNo` is null");
            return (Criteria) this;
        }

        public Criteria andBiznoIsNotNull() {
            addCriterion("`bizNo` is not null");
            return (Criteria) this;
        }

        public Criteria andBiznoEqualTo(String value) {
            addCriterion("`bizNo` =", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotEqualTo(String value) {
            addCriterion("`bizNo` <>", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoGreaterThan(String value) {
            addCriterion("`bizNo` >", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoGreaterThanOrEqualTo(String value) {
            addCriterion("`bizNo` >=", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLessThan(String value) {
            addCriterion("`bizNo` <", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLessThanOrEqualTo(String value) {
            addCriterion("`bizNo` <=", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLike(String value) {
            addCriterion("`bizNo` like", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotLike(String value) {
            addCriterion("`bizNo` not like", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoIn(List<String> values) {
            addCriterion("`bizNo` in", values, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotIn(List<String> values) {
            addCriterion("`bizNo` not in", values, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoBetween(String value1, String value2) {
            addCriterion("`bizNo` between", value1, value2, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotBetween(String value1, String value2) {
            addCriterion("`bizNo` not between", value1, value2, "bizno");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("`appId` is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("`appId` is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("`appId` =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("`appId` <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("`appId` >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("`appId` >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("`appId` <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("`appId` <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("`appId` like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("`appId` not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("`appId` in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("`appId` not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("`appId` between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("`appId` not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andPayindexIsNull() {
            addCriterion("`payIndex` is null");
            return (Criteria) this;
        }

        public Criteria andPayindexIsNotNull() {
            addCriterion("`payIndex` is not null");
            return (Criteria) this;
        }

        public Criteria andPayindexEqualTo(String value) {
            addCriterion("`payIndex` =", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexNotEqualTo(String value) {
            addCriterion("`payIndex` <>", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexGreaterThan(String value) {
            addCriterion("`payIndex` >", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexGreaterThanOrEqualTo(String value) {
            addCriterion("`payIndex` >=", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexLessThan(String value) {
            addCriterion("`payIndex` <", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexLessThanOrEqualTo(String value) {
            addCriterion("`payIndex` <=", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexLike(String value) {
            addCriterion("`payIndex` like", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexNotLike(String value) {
            addCriterion("`payIndex` not like", value, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexIn(List<String> values) {
            addCriterion("`payIndex` in", values, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexNotIn(List<String> values) {
            addCriterion("`payIndex` not in", values, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexBetween(String value1, String value2) {
            addCriterion("`payIndex` between", value1, value2, "payindex");
            return (Criteria) this;
        }

        public Criteria andPayindexNotBetween(String value1, String value2) {
            addCriterion("`payIndex` not between", value1, value2, "payindex");
            return (Criteria) this;
        }

        public Criteria andApproveresultIsNull() {
            addCriterion("`approveResult` is null");
            return (Criteria) this;
        }

        public Criteria andApproveresultIsNotNull() {
            addCriterion("`approveResult` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveresultEqualTo(String value) {
            addCriterion("`approveResult` =", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultNotEqualTo(String value) {
            addCriterion("`approveResult` <>", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultGreaterThan(String value) {
            addCriterion("`approveResult` >", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultGreaterThanOrEqualTo(String value) {
            addCriterion("`approveResult` >=", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultLessThan(String value) {
            addCriterion("`approveResult` <", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultLessThanOrEqualTo(String value) {
            addCriterion("`approveResult` <=", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultLike(String value) {
            addCriterion("`approveResult` like", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultNotLike(String value) {
            addCriterion("`approveResult` not like", value, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultIn(List<String> values) {
            addCriterion("`approveResult` in", values, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultNotIn(List<String> values) {
            addCriterion("`approveResult` not in", values, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultBetween(String value1, String value2) {
            addCriterion("`approveResult` between", value1, value2, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApproveresultNotBetween(String value1, String value2) {
            addCriterion("`approveResult` not between", value1, value2, "approveresult");
            return (Criteria) this;
        }

        public Criteria andApprovecreditIsNull() {
            addCriterion("`approveCredit` is null");
            return (Criteria) this;
        }

        public Criteria andApprovecreditIsNotNull() {
            addCriterion("`approveCredit` is not null");
            return (Criteria) this;
        }

        public Criteria andApprovecreditEqualTo(Integer value) {
            addCriterion("`approveCredit` =", value, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditNotEqualTo(Integer value) {
            addCriterion("`approveCredit` <>", value, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditGreaterThan(Integer value) {
            addCriterion("`approveCredit` >", value, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("`approveCredit` >=", value, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditLessThan(Integer value) {
            addCriterion("`approveCredit` <", value, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditLessThanOrEqualTo(Integer value) {
            addCriterion("`approveCredit` <=", value, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditIn(List<Integer> values) {
            addCriterion("`approveCredit` in", values, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditNotIn(List<Integer> values) {
            addCriterion("`approveCredit` not in", values, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditBetween(Integer value1, Integer value2) {
            addCriterion("`approveCredit` between", value1, value2, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApprovecreditNotBetween(Integer value1, Integer value2) {
            addCriterion("`approveCredit` not between", value1, value2, "approvecredit");
            return (Criteria) this;
        }

        public Criteria andApproveaprIsNull() {
            addCriterion("`approveAPR` is null");
            return (Criteria) this;
        }

        public Criteria andApproveaprIsNotNull() {
            addCriterion("`approveAPR` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveaprEqualTo(String value) {
            addCriterion("`approveAPR` =", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprNotEqualTo(String value) {
            addCriterion("`approveAPR` <>", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprGreaterThan(String value) {
            addCriterion("`approveAPR` >", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprGreaterThanOrEqualTo(String value) {
            addCriterion("`approveAPR` >=", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprLessThan(String value) {
            addCriterion("`approveAPR` <", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprLessThanOrEqualTo(String value) {
            addCriterion("`approveAPR` <=", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprLike(String value) {
            addCriterion("`approveAPR` like", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprNotLike(String value) {
            addCriterion("`approveAPR` not like", value, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprIn(List<String> values) {
            addCriterion("`approveAPR` in", values, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprNotIn(List<String> values) {
            addCriterion("`approveAPR` not in", values, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprBetween(String value1, String value2) {
            addCriterion("`approveAPR` between", value1, value2, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApproveaprNotBetween(String value1, String value2) {
            addCriterion("`approveAPR` not between", value1, value2, "approveapr");
            return (Criteria) this;
        }

        public Criteria andApprovedprIsNull() {
            addCriterion("`approveDPR` is null");
            return (Criteria) this;
        }

        public Criteria andApprovedprIsNotNull() {
            addCriterion("`approveDPR` is not null");
            return (Criteria) this;
        }

        public Criteria andApprovedprEqualTo(String value) {
            addCriterion("`approveDPR` =", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprNotEqualTo(String value) {
            addCriterion("`approveDPR` <>", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprGreaterThan(String value) {
            addCriterion("`approveDPR` >", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprGreaterThanOrEqualTo(String value) {
            addCriterion("`approveDPR` >=", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprLessThan(String value) {
            addCriterion("`approveDPR` <", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprLessThanOrEqualTo(String value) {
            addCriterion("`approveDPR` <=", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprLike(String value) {
            addCriterion("`approveDPR` like", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprNotLike(String value) {
            addCriterion("`approveDPR` not like", value, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprIn(List<String> values) {
            addCriterion("`approveDPR` in", values, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprNotIn(List<String> values) {
            addCriterion("`approveDPR` not in", values, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprBetween(String value1, String value2) {
            addCriterion("`approveDPR` between", value1, value2, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andApprovedprNotBetween(String value1, String value2) {
            addCriterion("`approveDPR` not between", value1, value2, "approvedpr");
            return (Criteria) this;
        }

        public Criteria andMinloantermIsNull() {
            addCriterion("`minLoanTerm` is null");
            return (Criteria) this;
        }

        public Criteria andMinloantermIsNotNull() {
            addCriterion("`minLoanTerm` is not null");
            return (Criteria) this;
        }

        public Criteria andMinloantermEqualTo(Integer value) {
            addCriterion("`minLoanTerm` =", value, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermNotEqualTo(Integer value) {
            addCriterion("`minLoanTerm` <>", value, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermGreaterThan(Integer value) {
            addCriterion("`minLoanTerm` >", value, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermGreaterThanOrEqualTo(Integer value) {
            addCriterion("`minLoanTerm` >=", value, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermLessThan(Integer value) {
            addCriterion("`minLoanTerm` <", value, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermLessThanOrEqualTo(Integer value) {
            addCriterion("`minLoanTerm` <=", value, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermIn(List<Integer> values) {
            addCriterion("`minLoanTerm` in", values, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermNotIn(List<Integer> values) {
            addCriterion("`minLoanTerm` not in", values, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermBetween(Integer value1, Integer value2) {
            addCriterion("`minLoanTerm` between", value1, value2, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMinloantermNotBetween(Integer value1, Integer value2) {
            addCriterion("`minLoanTerm` not between", value1, value2, "minloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermIsNull() {
            addCriterion("`maxLoanTerm` is null");
            return (Criteria) this;
        }

        public Criteria andMaxloantermIsNotNull() {
            addCriterion("`maxLoanTerm` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxloantermEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` =", value, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermNotEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` <>", value, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermGreaterThan(Integer value) {
            addCriterion("`maxLoanTerm` >", value, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermGreaterThanOrEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` >=", value, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermLessThan(Integer value) {
            addCriterion("`maxLoanTerm` <", value, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermLessThanOrEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` <=", value, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermIn(List<Integer> values) {
            addCriterion("`maxLoanTerm` in", values, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermNotIn(List<Integer> values) {
            addCriterion("`maxLoanTerm` not in", values, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermBetween(Integer value1, Integer value2) {
            addCriterion("`maxLoanTerm` between", value1, value2, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andMaxloantermNotBetween(Integer value1, Integer value2) {
            addCriterion("`maxLoanTerm` not between", value1, value2, "maxloanterm");
            return (Criteria) this;
        }

        public Criteria andRefusecodeIsNull() {
            addCriterion("`refuseCode` is null");
            return (Criteria) this;
        }

        public Criteria andRefusecodeIsNotNull() {
            addCriterion("`refuseCode` is not null");
            return (Criteria) this;
        }

        public Criteria andRefusecodeEqualTo(String value) {
            addCriterion("`refuseCode` =", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeNotEqualTo(String value) {
            addCriterion("`refuseCode` <>", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeGreaterThan(String value) {
            addCriterion("`refuseCode` >", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeGreaterThanOrEqualTo(String value) {
            addCriterion("`refuseCode` >=", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeLessThan(String value) {
            addCriterion("`refuseCode` <", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeLessThanOrEqualTo(String value) {
            addCriterion("`refuseCode` <=", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeLike(String value) {
            addCriterion("`refuseCode` like", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeNotLike(String value) {
            addCriterion("`refuseCode` not like", value, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeIn(List<String> values) {
            addCriterion("`refuseCode` in", values, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeNotIn(List<String> values) {
            addCriterion("`refuseCode` not in", values, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeBetween(String value1, String value2) {
            addCriterion("`refuseCode` between", value1, value2, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusecodeNotBetween(String value1, String value2) {
            addCriterion("`refuseCode` not between", value1, value2, "refusecode");
            return (Criteria) this;
        }

        public Criteria andRefusereasonIsNull() {
            addCriterion("`refuseReason` is null");
            return (Criteria) this;
        }

        public Criteria andRefusereasonIsNotNull() {
            addCriterion("`refuseReason` is not null");
            return (Criteria) this;
        }

        public Criteria andRefusereasonEqualTo(String value) {
            addCriterion("`refuseReason` =", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonNotEqualTo(String value) {
            addCriterion("`refuseReason` <>", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonGreaterThan(String value) {
            addCriterion("`refuseReason` >", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonGreaterThanOrEqualTo(String value) {
            addCriterion("`refuseReason` >=", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonLessThan(String value) {
            addCriterion("`refuseReason` <", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonLessThanOrEqualTo(String value) {
            addCriterion("`refuseReason` <=", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonLike(String value) {
            addCriterion("`refuseReason` like", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonNotLike(String value) {
            addCriterion("`refuseReason` not like", value, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonIn(List<String> values) {
            addCriterion("`refuseReason` in", values, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonNotIn(List<String> values) {
            addCriterion("`refuseReason` not in", values, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonBetween(String value1, String value2) {
            addCriterion("`refuseReason` between", value1, value2, "refusereason");
            return (Criteria) this;
        }

        public Criteria andRefusereasonNotBetween(String value1, String value2) {
            addCriterion("`refuseReason` not between", value1, value2, "refusereason");
            return (Criteria) this;
        }

        public Criteria andApprovetimeIsNull() {
            addCriterion("`approveTime` is null");
            return (Criteria) this;
        }

        public Criteria andApprovetimeIsNotNull() {
            addCriterion("`approveTime` is not null");
            return (Criteria) this;
        }

        public Criteria andApprovetimeEqualTo(Date value) {
            addCriterion("`approveTime` =", value, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeNotEqualTo(Date value) {
            addCriterion("`approveTime` <>", value, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeGreaterThan(Date value) {
            addCriterion("`approveTime` >", value, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`approveTime` >=", value, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeLessThan(Date value) {
            addCriterion("`approveTime` <", value, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeLessThanOrEqualTo(Date value) {
            addCriterion("`approveTime` <=", value, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeIn(List<Date> values) {
            addCriterion("`approveTime` in", values, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeNotIn(List<Date> values) {
            addCriterion("`approveTime` not in", values, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeBetween(Date value1, Date value2) {
            addCriterion("`approveTime` between", value1, value2, "approvetime");
            return (Criteria) this;
        }

        public Criteria andApprovetimeNotBetween(Date value1, Date value2) {
            addCriterion("`approveTime` not between", value1, value2, "approvetime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("`createTime` is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("`createTime` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("`createTime` =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("`createTime` <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("`createTime` >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`createTime` >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("`createTime` <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("`createTime` <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("`createTime` in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("`createTime` not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("`createTime` between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("`createTime` not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_approveResult
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 06 15:01:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}