package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApproveResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public ApproveResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("`userId` is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("`userId` is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("`userId` =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("`userId` <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("`userId` >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`userId` >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("`userId` <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("`userId` <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("`userId` like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("`userId` not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("`userId` in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("`userId` not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("`userId` between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("`userId` not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBiznoIsNull() {
            addCriterion("`bizno` is null");
            return (Criteria) this;
        }

        public Criteria andBiznoIsNotNull() {
            addCriterion("`bizno` is not null");
            return (Criteria) this;
        }

        public Criteria andBiznoEqualTo(String value) {
            addCriterion("`bizno` =", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotEqualTo(String value) {
            addCriterion("`bizno` <>", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoGreaterThan(String value) {
            addCriterion("`bizno` >", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoGreaterThanOrEqualTo(String value) {
            addCriterion("`bizno` >=", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLessThan(String value) {
            addCriterion("`bizno` <", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLessThanOrEqualTo(String value) {
            addCriterion("`bizno` <=", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoLike(String value) {
            addCriterion("`bizno` like", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotLike(String value) {
            addCriterion("`bizno` not like", value, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoIn(List<String> values) {
            addCriterion("`bizno` in", values, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotIn(List<String> values) {
            addCriterion("`bizno` not in", values, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoBetween(String value1, String value2) {
            addCriterion("`bizno` between", value1, value2, "bizno");
            return (Criteria) this;
        }

        public Criteria andBiznoNotBetween(String value1, String value2) {
            addCriterion("`bizno` not between", value1, value2, "bizno");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("`applyId` is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("`applyId` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(String value) {
            addCriterion("`applyId` =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(String value) {
            addCriterion("`applyId` <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(String value) {
            addCriterion("`applyId` >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("`applyId` >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(String value) {
            addCriterion("`applyId` <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(String value) {
            addCriterion("`applyId` <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLike(String value) {
            addCriterion("`applyId` like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotLike(String value) {
            addCriterion("`applyId` not like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<String> values) {
            addCriterion("`applyId` in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<String> values) {
            addCriterion("`applyId` not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(String value1, String value2) {
            addCriterion("`applyId` between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(String value1, String value2) {
            addCriterion("`applyId` not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andPayIndexIsNull() {
            addCriterion("`payIndex` is null");
            return (Criteria) this;
        }

        public Criteria andPayIndexIsNotNull() {
            addCriterion("`payIndex` is not null");
            return (Criteria) this;
        }

        public Criteria andPayIndexEqualTo(String value) {
            addCriterion("`payIndex` =", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexNotEqualTo(String value) {
            addCriterion("`payIndex` <>", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexGreaterThan(String value) {
            addCriterion("`payIndex` >", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexGreaterThanOrEqualTo(String value) {
            addCriterion("`payIndex` >=", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexLessThan(String value) {
            addCriterion("`payIndex` <", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexLessThanOrEqualTo(String value) {
            addCriterion("`payIndex` <=", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexLike(String value) {
            addCriterion("`payIndex` like", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexNotLike(String value) {
            addCriterion("`payIndex` not like", value, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexIn(List<String> values) {
            addCriterion("`payIndex` in", values, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexNotIn(List<String> values) {
            addCriterion("`payIndex` not in", values, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexBetween(String value1, String value2) {
            addCriterion("`payIndex` between", value1, value2, "payIndex");
            return (Criteria) this;
        }

        public Criteria andPayIndexNotBetween(String value1, String value2) {
            addCriterion("`payIndex` not between", value1, value2, "payIndex");
            return (Criteria) this;
        }

        public Criteria andApproveResultIsNull() {
            addCriterion("`approveResult` is null");
            return (Criteria) this;
        }

        public Criteria andApproveResultIsNotNull() {
            addCriterion("`approveResult` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveResultEqualTo(String value) {
            addCriterion("`approveResult` =", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotEqualTo(String value) {
            addCriterion("`approveResult` <>", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultGreaterThan(String value) {
            addCriterion("`approveResult` >", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultGreaterThanOrEqualTo(String value) {
            addCriterion("`approveResult` >=", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultLessThan(String value) {
            addCriterion("`approveResult` <", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultLessThanOrEqualTo(String value) {
            addCriterion("`approveResult` <=", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultLike(String value) {
            addCriterion("`approveResult` like", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotLike(String value) {
            addCriterion("`approveResult` not like", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultIn(List<String> values) {
            addCriterion("`approveResult` in", values, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotIn(List<String> values) {
            addCriterion("`approveResult` not in", values, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultBetween(String value1, String value2) {
            addCriterion("`approveResult` between", value1, value2, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotBetween(String value1, String value2) {
            addCriterion("`approveResult` not between", value1, value2, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveCreditIsNull() {
            addCriterion("`approveCredit` is null");
            return (Criteria) this;
        }

        public Criteria andApproveCreditIsNotNull() {
            addCriterion("`approveCredit` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveCreditEqualTo(Integer value) {
            addCriterion("`approveCredit` =", value, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditNotEqualTo(Integer value) {
            addCriterion("`approveCredit` <>", value, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditGreaterThan(Integer value) {
            addCriterion("`approveCredit` >", value, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditGreaterThanOrEqualTo(Integer value) {
            addCriterion("`approveCredit` >=", value, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditLessThan(Integer value) {
            addCriterion("`approveCredit` <", value, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditLessThanOrEqualTo(Integer value) {
            addCriterion("`approveCredit` <=", value, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditIn(List<Integer> values) {
            addCriterion("`approveCredit` in", values, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditNotIn(List<Integer> values) {
            addCriterion("`approveCredit` not in", values, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditBetween(Integer value1, Integer value2) {
            addCriterion("`approveCredit` between", value1, value2, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveCreditNotBetween(Integer value1, Integer value2) {
            addCriterion("`approveCredit` not between", value1, value2, "approveCredit");
            return (Criteria) this;
        }

        public Criteria andApproveAPRIsNull() {
            addCriterion("`approveAPR` is null");
            return (Criteria) this;
        }

        public Criteria andApproveAPRIsNotNull() {
            addCriterion("`approveAPR` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveAPREqualTo(String value) {
            addCriterion("`approveAPR` =", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRNotEqualTo(String value) {
            addCriterion("`approveAPR` <>", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRGreaterThan(String value) {
            addCriterion("`approveAPR` >", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRGreaterThanOrEqualTo(String value) {
            addCriterion("`approveAPR` >=", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRLessThan(String value) {
            addCriterion("`approveAPR` <", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRLessThanOrEqualTo(String value) {
            addCriterion("`approveAPR` <=", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRLike(String value) {
            addCriterion("`approveAPR` like", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRNotLike(String value) {
            addCriterion("`approveAPR` not like", value, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRIn(List<String> values) {
            addCriterion("`approveAPR` in", values, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRNotIn(List<String> values) {
            addCriterion("`approveAPR` not in", values, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRBetween(String value1, String value2) {
            addCriterion("`approveAPR` between", value1, value2, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveAPRNotBetween(String value1, String value2) {
            addCriterion("`approveAPR` not between", value1, value2, "approveAPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRIsNull() {
            addCriterion("`approveDPR` is null");
            return (Criteria) this;
        }

        public Criteria andApproveDPRIsNotNull() {
            addCriterion("`approveDPR` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveDPREqualTo(String value) {
            addCriterion("`approveDPR` =", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRNotEqualTo(String value) {
            addCriterion("`approveDPR` <>", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRGreaterThan(String value) {
            addCriterion("`approveDPR` >", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRGreaterThanOrEqualTo(String value) {
            addCriterion("`approveDPR` >=", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRLessThan(String value) {
            addCriterion("`approveDPR` <", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRLessThanOrEqualTo(String value) {
            addCriterion("`approveDPR` <=", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRLike(String value) {
            addCriterion("`approveDPR` like", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRNotLike(String value) {
            addCriterion("`approveDPR` not like", value, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRIn(List<String> values) {
            addCriterion("`approveDPR` in", values, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRNotIn(List<String> values) {
            addCriterion("`approveDPR` not in", values, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRBetween(String value1, String value2) {
            addCriterion("`approveDPR` between", value1, value2, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andApproveDPRNotBetween(String value1, String value2) {
            addCriterion("`approveDPR` not between", value1, value2, "approveDPR");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermIsNull() {
            addCriterion("`minLoanTerm` is null");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermIsNotNull() {
            addCriterion("`minLoanTerm` is not null");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermEqualTo(Integer value) {
            addCriterion("`minLoanTerm` =", value, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermNotEqualTo(Integer value) {
            addCriterion("`minLoanTerm` <>", value, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermGreaterThan(Integer value) {
            addCriterion("`minLoanTerm` >", value, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("`minLoanTerm` >=", value, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermLessThan(Integer value) {
            addCriterion("`minLoanTerm` <", value, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermLessThanOrEqualTo(Integer value) {
            addCriterion("`minLoanTerm` <=", value, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermIn(List<Integer> values) {
            addCriterion("`minLoanTerm` in", values, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermNotIn(List<Integer> values) {
            addCriterion("`minLoanTerm` not in", values, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermBetween(Integer value1, Integer value2) {
            addCriterion("`minLoanTerm` between", value1, value2, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMinLoanTermNotBetween(Integer value1, Integer value2) {
            addCriterion("`minLoanTerm` not between", value1, value2, "minLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermIsNull() {
            addCriterion("`maxLoanTerm` is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermIsNotNull() {
            addCriterion("`maxLoanTerm` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` =", value, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermNotEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` <>", value, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermGreaterThan(Integer value) {
            addCriterion("`maxLoanTerm` >", value, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` >=", value, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermLessThan(Integer value) {
            addCriterion("`maxLoanTerm` <", value, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermLessThanOrEqualTo(Integer value) {
            addCriterion("`maxLoanTerm` <=", value, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermIn(List<Integer> values) {
            addCriterion("`maxLoanTerm` in", values, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermNotIn(List<Integer> values) {
            addCriterion("`maxLoanTerm` not in", values, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermBetween(Integer value1, Integer value2) {
            addCriterion("`maxLoanTerm` between", value1, value2, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andMaxLoanTermNotBetween(Integer value1, Integer value2) {
            addCriterion("`maxLoanTerm` not between", value1, value2, "maxLoanTerm");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeIsNull() {
            addCriterion("`refuseCode` is null");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeIsNotNull() {
            addCriterion("`refuseCode` is not null");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeEqualTo(String value) {
            addCriterion("`refuseCode` =", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeNotEqualTo(String value) {
            addCriterion("`refuseCode` <>", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeGreaterThan(String value) {
            addCriterion("`refuseCode` >", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`refuseCode` >=", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeLessThan(String value) {
            addCriterion("`refuseCode` <", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeLessThanOrEqualTo(String value) {
            addCriterion("`refuseCode` <=", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeLike(String value) {
            addCriterion("`refuseCode` like", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeNotLike(String value) {
            addCriterion("`refuseCode` not like", value, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeIn(List<String> values) {
            addCriterion("`refuseCode` in", values, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeNotIn(List<String> values) {
            addCriterion("`refuseCode` not in", values, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeBetween(String value1, String value2) {
            addCriterion("`refuseCode` between", value1, value2, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseCodeNotBetween(String value1, String value2) {
            addCriterion("`refuseCode` not between", value1, value2, "refuseCode");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonIsNull() {
            addCriterion("`refuseReason` is null");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonIsNotNull() {
            addCriterion("`refuseReason` is not null");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonEqualTo(String value) {
            addCriterion("`refuseReason` =", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonNotEqualTo(String value) {
            addCriterion("`refuseReason` <>", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonGreaterThan(String value) {
            addCriterion("`refuseReason` >", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonGreaterThanOrEqualTo(String value) {
            addCriterion("`refuseReason` >=", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonLessThan(String value) {
            addCriterion("`refuseReason` <", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonLessThanOrEqualTo(String value) {
            addCriterion("`refuseReason` <=", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonLike(String value) {
            addCriterion("`refuseReason` like", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonNotLike(String value) {
            addCriterion("`refuseReason` not like", value, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonIn(List<String> values) {
            addCriterion("`refuseReason` in", values, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonNotIn(List<String> values) {
            addCriterion("`refuseReason` not in", values, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonBetween(String value1, String value2) {
            addCriterion("`refuseReason` between", value1, value2, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andRefuseReasonNotBetween(String value1, String value2) {
            addCriterion("`refuseReason` not between", value1, value2, "refuseReason");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNull() {
            addCriterion("`approveTime` is null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIsNotNull() {
            addCriterion("`approveTime` is not null");
            return (Criteria) this;
        }

        public Criteria andApproveTimeEqualTo(Date value) {
            addCriterion("`approveTime` =", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotEqualTo(Date value) {
            addCriterion("`approveTime` <>", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThan(Date value) {
            addCriterion("`approveTime` >", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`approveTime` >=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThan(Date value) {
            addCriterion("`approveTime` <", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeLessThanOrEqualTo(Date value) {
            addCriterion("`approveTime` <=", value, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeIn(List<Date> values) {
            addCriterion("`approveTime` in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotIn(List<Date> values) {
            addCriterion("`approveTime` not in", values, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeBetween(Date value1, Date value2) {
            addCriterion("`approveTime` between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andApproveTimeNotBetween(Date value1, Date value2) {
            addCriterion("`approveTime` not between", value1, value2, "approveTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`createTime` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`createTime` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`createTime` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`createTime` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`createTime` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`createTime` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`createTime` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`createTime` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`createTime` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`createTime` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`createTime` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`createTime` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`updateTime` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`updateTime` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`updateTime` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`updateTime` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`updateTime` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`updateTime` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`updateTime` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`updateTime` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`updateTime` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`updateTime` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`updateTime` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`updateTime` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_approveResult
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 20 12:09:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 20 12:09:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}