package com.zdd.risk.bean;

import java.util.Date;

public class ApproveResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.id
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.userId
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.bizNo
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String bizno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.appId
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.payIndex
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String payindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String approveresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.approveCredit
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private Integer approvecredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.approveAPR
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String approveapr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.approveDPR
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String approvedpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.minLoanTerm
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private Integer minloanterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.maxLoanTerm
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private Integer maxloanterm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.refuseCode
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String refusecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.refuseReason
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String refusereason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.approveTime
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private Date approvetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.createTime
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_approveResult.remark
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.id
     *
     * @return the value of risk_approveResult.id
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.id
     *
     * @param id the value for risk_approveResult.id
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.userId
     *
     * @return the value of risk_approveResult.userId
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.userId
     *
     * @param userid the value for risk_approveResult.userId
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.bizNo
     *
     * @return the value of risk_approveResult.bizNo
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getBizno() {
        return bizno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.bizNo
     *
     * @param bizno the value for risk_approveResult.bizNo
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setBizno(String bizno) {
        this.bizno = bizno == null ? null : bizno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.appId
     *
     * @return the value of risk_approveResult.appId
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.appId
     *
     * @param appid the value for risk_approveResult.appId
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.payIndex
     *
     * @return the value of risk_approveResult.payIndex
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getPayindex() {
        return payindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.payIndex
     *
     * @param payindex the value for risk_approveResult.payIndex
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setPayindex(String payindex) {
        this.payindex = payindex == null ? null : payindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.approveResult
     *
     * @return the value of risk_approveResult.approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getApproveresult() {
        return approveresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.approveResult
     *
     * @param approveresult the value for risk_approveResult.approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setApproveresult(String approveresult) {
        this.approveresult = approveresult == null ? null : approveresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.approveCredit
     *
     * @return the value of risk_approveResult.approveCredit
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Integer getApprovecredit() {
        return approvecredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.approveCredit
     *
     * @param approvecredit the value for risk_approveResult.approveCredit
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setApprovecredit(Integer approvecredit) {
        this.approvecredit = approvecredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.approveAPR
     *
     * @return the value of risk_approveResult.approveAPR
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getApproveapr() {
        return approveapr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.approveAPR
     *
     * @param approveapr the value for risk_approveResult.approveAPR
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setApproveapr(String approveapr) {
        this.approveapr = approveapr == null ? null : approveapr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.approveDPR
     *
     * @return the value of risk_approveResult.approveDPR
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getApprovedpr() {
        return approvedpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.approveDPR
     *
     * @param approvedpr the value for risk_approveResult.approveDPR
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setApprovedpr(String approvedpr) {
        this.approvedpr = approvedpr == null ? null : approvedpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.minLoanTerm
     *
     * @return the value of risk_approveResult.minLoanTerm
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Integer getMinloanterm() {
        return minloanterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.minLoanTerm
     *
     * @param minloanterm the value for risk_approveResult.minLoanTerm
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setMinloanterm(Integer minloanterm) {
        this.minloanterm = minloanterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.maxLoanTerm
     *
     * @return the value of risk_approveResult.maxLoanTerm
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Integer getMaxloanterm() {
        return maxloanterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.maxLoanTerm
     *
     * @param maxloanterm the value for risk_approveResult.maxLoanTerm
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setMaxloanterm(Integer maxloanterm) {
        this.maxloanterm = maxloanterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.refuseCode
     *
     * @return the value of risk_approveResult.refuseCode
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getRefusecode() {
        return refusecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.refuseCode
     *
     * @param refusecode the value for risk_approveResult.refuseCode
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setRefusecode(String refusecode) {
        this.refusecode = refusecode == null ? null : refusecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.refuseReason
     *
     * @return the value of risk_approveResult.refuseReason
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getRefusereason() {
        return refusereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.refuseReason
     *
     * @param refusereason the value for risk_approveResult.refuseReason
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setRefusereason(String refusereason) {
        this.refusereason = refusereason == null ? null : refusereason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.approveTime
     *
     * @return the value of risk_approveResult.approveTime
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Date getApprovetime() {
        return approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.approveTime
     *
     * @param approvetime the value for risk_approveResult.approveTime
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setApprovetime(Date approvetime) {
        this.approvetime = approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.createTime
     *
     * @return the value of risk_approveResult.createTime
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.createTime
     *
     * @param createtime the value for risk_approveResult.createTime
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_approveResult.remark
     *
     * @return the value of risk_approveResult.remark
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_approveResult.remark
     *
     * @param remark the value for risk_approveResult.remark
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}