package com.zdd.risk.bean;

import java.util.Date;

public class Certification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.id
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.userId
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.idCard
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.mobile
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.certificationType
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String certificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.certificationItem
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String certificationItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.certificationLimit
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private Date certificationLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.flag
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.remark
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.creatTime
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_certification.certificationResult
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    private String certificationResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.id
     *
     * @return the value of risk_certification.id
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.id
     *
     * @param id the value for risk_certification.id
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.userId
     *
     * @return the value of risk_certification.userId
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.userId
     *
     * @param userId the value for risk_certification.userId
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.idCard
     *
     * @return the value of risk_certification.idCard
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.idCard
     *
     * @param idCard the value for risk_certification.idCard
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.mobile
     *
     * @return the value of risk_certification.mobile
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.mobile
     *
     * @param mobile the value for risk_certification.mobile
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.certificationType
     *
     * @return the value of risk_certification.certificationType
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getCertificationType() {
        return certificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.certificationType
     *
     * @param certificationType the value for risk_certification.certificationType
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setCertificationType(String certificationType) {
        this.certificationType = certificationType == null ? null : certificationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.certificationItem
     *
     * @return the value of risk_certification.certificationItem
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getCertificationItem() {
        return certificationItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.certificationItem
     *
     * @param certificationItem the value for risk_certification.certificationItem
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setCertificationItem(String certificationItem) {
        this.certificationItem = certificationItem == null ? null : certificationItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.certificationLimit
     *
     * @return the value of risk_certification.certificationLimit
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public Date getCertificationLimit() {
        return certificationLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.certificationLimit
     *
     * @param certificationLimit the value for risk_certification.certificationLimit
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setCertificationLimit(Date certificationLimit) {
        this.certificationLimit = certificationLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.flag
     *
     * @return the value of risk_certification.flag
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.flag
     *
     * @param flag the value for risk_certification.flag
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.remark
     *
     * @return the value of risk_certification.remark
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.remark
     *
     * @param remark the value for risk_certification.remark
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.creatTime
     *
     * @return the value of risk_certification.creatTime
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.creatTime
     *
     * @param creatTime the value for risk_certification.creatTime
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column risk_certification.certificationResult
     *
     * @return the value of risk_certification.certificationResult
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getCertificationResult() {
        return certificationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column risk_certification.certificationResult
     *
     * @param certificationResult the value for risk_certification.certificationResult
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setCertificationResult(String certificationResult) {
        this.certificationResult = certificationResult == null ? null : certificationResult.trim();
    }
}