package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CertificationUserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public CertificationUserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("`userId` is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("`userId` is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("`userId` =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("`userId` <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("`userId` >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`userId` >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("`userId` <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("`userId` <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("`userId` like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("`userId` not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("`userId` in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("`userId` not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("`userId` between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("`userId` not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("`mobile` is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("`mobile` is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("`mobile` =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("`mobile` <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("`mobile` >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("`mobile` >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("`mobile` <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("`mobile` <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("`mobile` like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("`mobile` not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("`mobile` in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("`mobile` not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("`mobile` between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("`mobile` not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("`realName` is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("`realName` is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("`realName` =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("`realName` <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("`realName` >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("`realName` >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("`realName` <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("`realName` <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("`realName` like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("`realName` not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("`realName` in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("`realName` not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("`realName` between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("`realName` not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("`nation` is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("`nation` is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("`nation` =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("`nation` <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("`nation` >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("`nation` >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("`nation` <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("`nation` <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("`nation` like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("`nation` not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("`nation` in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("`nation` not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("`nation` between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("`nation` not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("`age` is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("`age` is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("`age` =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("`age` <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("`age` >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`age` >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("`age` <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("`age` <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("`age` in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("`age` not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("`age` between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("`age` not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentIsNull() {
            addCriterion("`addressPermanent` is null");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentIsNotNull() {
            addCriterion("`addressPermanent` is not null");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentEqualTo(String value) {
            addCriterion("`addressPermanent` =", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentNotEqualTo(String value) {
            addCriterion("`addressPermanent` <>", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentGreaterThan(String value) {
            addCriterion("`addressPermanent` >", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentGreaterThanOrEqualTo(String value) {
            addCriterion("`addressPermanent` >=", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentLessThan(String value) {
            addCriterion("`addressPermanent` <", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentLessThanOrEqualTo(String value) {
            addCriterion("`addressPermanent` <=", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentLike(String value) {
            addCriterion("`addressPermanent` like", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentNotLike(String value) {
            addCriterion("`addressPermanent` not like", value, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentIn(List<String> values) {
            addCriterion("`addressPermanent` in", values, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentNotIn(List<String> values) {
            addCriterion("`addressPermanent` not in", values, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentBetween(String value1, String value2) {
            addCriterion("`addressPermanent` between", value1, value2, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andAddressPermanentNotBetween(String value1, String value2) {
            addCriterion("`addressPermanent` not between", value1, value2, "addressPermanent");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateIsNull() {
            addCriterion("`idCardValidDate` is null");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateIsNotNull() {
            addCriterion("`idCardValidDate` is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateEqualTo(String value) {
            addCriterion("`idCardValidDate` =", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateNotEqualTo(String value) {
            addCriterion("`idCardValidDate` <>", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateGreaterThan(String value) {
            addCriterion("`idCardValidDate` >", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateGreaterThanOrEqualTo(String value) {
            addCriterion("`idCardValidDate` >=", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateLessThan(String value) {
            addCriterion("`idCardValidDate` <", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateLessThanOrEqualTo(String value) {
            addCriterion("`idCardValidDate` <=", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateLike(String value) {
            addCriterion("`idCardValidDate` like", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateNotLike(String value) {
            addCriterion("`idCardValidDate` not like", value, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateIn(List<String> values) {
            addCriterion("`idCardValidDate` in", values, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateNotIn(List<String> values) {
            addCriterion("`idCardValidDate` not in", values, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateBetween(String value1, String value2) {
            addCriterion("`idCardValidDate` between", value1, value2, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andIdCardValidDateNotBetween(String value1, String value2) {
            addCriterion("`idCardValidDate` not between", value1, value2, "idCardValidDate");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNull() {
            addCriterion("`maritalStatus` is null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNotNull() {
            addCriterion("`maritalStatus` is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusEqualTo(Integer value) {
            addCriterion("`maritalStatus` =", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotEqualTo(Integer value) {
            addCriterion("`maritalStatus` <>", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThan(Integer value) {
            addCriterion("`maritalStatus` >", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`maritalStatus` >=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThan(Integer value) {
            addCriterion("`maritalStatus` <", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`maritalStatus` <=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIn(List<Integer> values) {
            addCriterion("`maritalStatus` in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotIn(List<Integer> values) {
            addCriterion("`maritalStatus` not in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusBetween(Integer value1, Integer value2) {
            addCriterion("`maritalStatus` between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`maritalStatus` not between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andEducationIsNull() {
            addCriterion("`education` is null");
            return (Criteria) this;
        }

        public Criteria andEducationIsNotNull() {
            addCriterion("`education` is not null");
            return (Criteria) this;
        }

        public Criteria andEducationEqualTo(Integer value) {
            addCriterion("`education` =", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotEqualTo(Integer value) {
            addCriterion("`education` <>", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThan(Integer value) {
            addCriterion("`education` >", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThanOrEqualTo(Integer value) {
            addCriterion("`education` >=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThan(Integer value) {
            addCriterion("`education` <", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThanOrEqualTo(Integer value) {
            addCriterion("`education` <=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationIn(List<Integer> values) {
            addCriterion("`education` in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotIn(List<Integer> values) {
            addCriterion("`education` not in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationBetween(Integer value1, Integer value2) {
            addCriterion("`education` between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotBetween(Integer value1, Integer value2) {
            addCriterion("`education` not between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andInstitutionIsNull() {
            addCriterion("`institution` is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionIsNotNull() {
            addCriterion("`institution` is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionEqualTo(String value) {
            addCriterion("`institution` =", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotEqualTo(String value) {
            addCriterion("`institution` <>", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionGreaterThan(String value) {
            addCriterion("`institution` >", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionGreaterThanOrEqualTo(String value) {
            addCriterion("`institution` >=", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLessThan(String value) {
            addCriterion("`institution` <", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLessThanOrEqualTo(String value) {
            addCriterion("`institution` <=", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionLike(String value) {
            addCriterion("`institution` like", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotLike(String value) {
            addCriterion("`institution` not like", value, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionIn(List<String> values) {
            addCriterion("`institution` in", values, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotIn(List<String> values) {
            addCriterion("`institution` not in", values, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionBetween(String value1, String value2) {
            addCriterion("`institution` between", value1, value2, "institution");
            return (Criteria) this;
        }

        public Criteria andInstitutionNotBetween(String value1, String value2) {
            addCriterion("`institution` not between", value1, value2, "institution");
            return (Criteria) this;
        }

        public Criteria andAddressWorkIsNull() {
            addCriterion("`addressWork` is null");
            return (Criteria) this;
        }

        public Criteria andAddressWorkIsNotNull() {
            addCriterion("`addressWork` is not null");
            return (Criteria) this;
        }

        public Criteria andAddressWorkEqualTo(String value) {
            addCriterion("`addressWork` =", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkNotEqualTo(String value) {
            addCriterion("`addressWork` <>", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkGreaterThan(String value) {
            addCriterion("`addressWork` >", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkGreaterThanOrEqualTo(String value) {
            addCriterion("`addressWork` >=", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkLessThan(String value) {
            addCriterion("`addressWork` <", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkLessThanOrEqualTo(String value) {
            addCriterion("`addressWork` <=", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkLike(String value) {
            addCriterion("`addressWork` like", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkNotLike(String value) {
            addCriterion("`addressWork` not like", value, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkIn(List<String> values) {
            addCriterion("`addressWork` in", values, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkNotIn(List<String> values) {
            addCriterion("`addressWork` not in", values, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkBetween(String value1, String value2) {
            addCriterion("`addressWork` between", value1, value2, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressWorkNotBetween(String value1, String value2) {
            addCriterion("`addressWork` not between", value1, value2, "addressWork");
            return (Criteria) this;
        }

        public Criteria andAddressHomeIsNull() {
            addCriterion("`addressHome` is null");
            return (Criteria) this;
        }

        public Criteria andAddressHomeIsNotNull() {
            addCriterion("`addressHome` is not null");
            return (Criteria) this;
        }

        public Criteria andAddressHomeEqualTo(String value) {
            addCriterion("`addressHome` =", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeNotEqualTo(String value) {
            addCriterion("`addressHome` <>", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeGreaterThan(String value) {
            addCriterion("`addressHome` >", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeGreaterThanOrEqualTo(String value) {
            addCriterion("`addressHome` >=", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeLessThan(String value) {
            addCriterion("`addressHome` <", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeLessThanOrEqualTo(String value) {
            addCriterion("`addressHome` <=", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeLike(String value) {
            addCriterion("`addressHome` like", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeNotLike(String value) {
            addCriterion("`addressHome` not like", value, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeIn(List<String> values) {
            addCriterion("`addressHome` in", values, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeNotIn(List<String> values) {
            addCriterion("`addressHome` not in", values, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeBetween(String value1, String value2) {
            addCriterion("`addressHome` between", value1, value2, "addressHome");
            return (Criteria) this;
        }

        public Criteria andAddressHomeNotBetween(String value1, String value2) {
            addCriterion("`addressHome` not between", value1, value2, "addressHome");
            return (Criteria) this;
        }

        public Criteria andPaydayIsNull() {
            addCriterion("`payday` is null");
            return (Criteria) this;
        }

        public Criteria andPaydayIsNotNull() {
            addCriterion("`payday` is not null");
            return (Criteria) this;
        }

        public Criteria andPaydayEqualTo(String value) {
            addCriterion("`payday` =", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayNotEqualTo(String value) {
            addCriterion("`payday` <>", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayGreaterThan(String value) {
            addCriterion("`payday` >", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayGreaterThanOrEqualTo(String value) {
            addCriterion("`payday` >=", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayLessThan(String value) {
            addCriterion("`payday` <", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayLessThanOrEqualTo(String value) {
            addCriterion("`payday` <=", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayLike(String value) {
            addCriterion("`payday` like", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayNotLike(String value) {
            addCriterion("`payday` not like", value, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayIn(List<String> values) {
            addCriterion("`payday` in", values, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayNotIn(List<String> values) {
            addCriterion("`payday` not in", values, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayBetween(String value1, String value2) {
            addCriterion("`payday` between", value1, value2, "payday");
            return (Criteria) this;
        }

        public Criteria andPaydayNotBetween(String value1, String value2) {
            addCriterion("`payday` not between", value1, value2, "payday");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("`companyName` is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("`companyName` is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("`companyName` =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("`companyName` <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("`companyName` >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("`companyName` >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("`companyName` <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("`companyName` <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("`companyName` like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("`companyName` not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("`companyName` in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("`companyName` not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("`companyName` between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("`companyName` not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneIsNull() {
            addCriterion("`companyPhone` is null");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneIsNotNull() {
            addCriterion("`companyPhone` is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneEqualTo(String value) {
            addCriterion("`companyPhone` =", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneNotEqualTo(String value) {
            addCriterion("`companyPhone` <>", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneGreaterThan(String value) {
            addCriterion("`companyPhone` >", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("`companyPhone` >=", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneLessThan(String value) {
            addCriterion("`companyPhone` <", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneLessThanOrEqualTo(String value) {
            addCriterion("`companyPhone` <=", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneLike(String value) {
            addCriterion("`companyPhone` like", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneNotLike(String value) {
            addCriterion("`companyPhone` not like", value, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneIn(List<String> values) {
            addCriterion("`companyPhone` in", values, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneNotIn(List<String> values) {
            addCriterion("`companyPhone` not in", values, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneBetween(String value1, String value2) {
            addCriterion("`companyPhone` between", value1, value2, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andCompanyPhoneNotBetween(String value1, String value2) {
            addCriterion("`companyPhone` not between", value1, value2, "companyPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactNameIsNull() {
            addCriterion("`sosContactName` is null");
            return (Criteria) this;
        }

        public Criteria andSosContactNameIsNotNull() {
            addCriterion("`sosContactName` is not null");
            return (Criteria) this;
        }

        public Criteria andSosContactNameEqualTo(String value) {
            addCriterion("`sosContactName` =", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameNotEqualTo(String value) {
            addCriterion("`sosContactName` <>", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameGreaterThan(String value) {
            addCriterion("`sosContactName` >", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameGreaterThanOrEqualTo(String value) {
            addCriterion("`sosContactName` >=", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameLessThan(String value) {
            addCriterion("`sosContactName` <", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameLessThanOrEqualTo(String value) {
            addCriterion("`sosContactName` <=", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameLike(String value) {
            addCriterion("`sosContactName` like", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameNotLike(String value) {
            addCriterion("`sosContactName` not like", value, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameIn(List<String> values) {
            addCriterion("`sosContactName` in", values, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameNotIn(List<String> values) {
            addCriterion("`sosContactName` not in", values, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameBetween(String value1, String value2) {
            addCriterion("`sosContactName` between", value1, value2, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactNameNotBetween(String value1, String value2) {
            addCriterion("`sosContactName` not between", value1, value2, "sosContactName");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationIsNull() {
            addCriterion("`sosContactRelation` is null");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationIsNotNull() {
            addCriterion("`sosContactRelation` is not null");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationEqualTo(Integer value) {
            addCriterion("`sosContactRelation` =", value, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationNotEqualTo(Integer value) {
            addCriterion("`sosContactRelation` <>", value, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationGreaterThan(Integer value) {
            addCriterion("`sosContactRelation` >", value, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationGreaterThanOrEqualTo(Integer value) {
            addCriterion("`sosContactRelation` >=", value, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationLessThan(Integer value) {
            addCriterion("`sosContactRelation` <", value, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationLessThanOrEqualTo(Integer value) {
            addCriterion("`sosContactRelation` <=", value, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationIn(List<Integer> values) {
            addCriterion("`sosContactRelation` in", values, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationNotIn(List<Integer> values) {
            addCriterion("`sosContactRelation` not in", values, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationBetween(Integer value1, Integer value2) {
            addCriterion("`sosContactRelation` between", value1, value2, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactRelationNotBetween(Integer value1, Integer value2) {
            addCriterion("`sosContactRelation` not between", value1, value2, "sosContactRelation");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneIsNull() {
            addCriterion("`sosContactPhone` is null");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneIsNotNull() {
            addCriterion("`sosContactPhone` is not null");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneEqualTo(String value) {
            addCriterion("`sosContactPhone` =", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneNotEqualTo(String value) {
            addCriterion("`sosContactPhone` <>", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneGreaterThan(String value) {
            addCriterion("`sosContactPhone` >", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("`sosContactPhone` >=", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneLessThan(String value) {
            addCriterion("`sosContactPhone` <", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("`sosContactPhone` <=", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneLike(String value) {
            addCriterion("`sosContactPhone` like", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneNotLike(String value) {
            addCriterion("`sosContactPhone` not like", value, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneIn(List<String> values) {
            addCriterion("`sosContactPhone` in", values, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneNotIn(List<String> values) {
            addCriterion("`sosContactPhone` not in", values, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneBetween(String value1, String value2) {
            addCriterion("`sosContactPhone` between", value1, value2, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactPhoneNotBetween(String value1, String value2) {
            addCriterion("`sosContactPhone` not between", value1, value2, "sosContactPhone");
            return (Criteria) this;
        }

        public Criteria andSosContactName1IsNull() {
            addCriterion("`sosContactName1` is null");
            return (Criteria) this;
        }

        public Criteria andSosContactName1IsNotNull() {
            addCriterion("`sosContactName1` is not null");
            return (Criteria) this;
        }

        public Criteria andSosContactName1EqualTo(String value) {
            addCriterion("`sosContactName1` =", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1NotEqualTo(String value) {
            addCriterion("`sosContactName1` <>", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1GreaterThan(String value) {
            addCriterion("`sosContactName1` >", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1GreaterThanOrEqualTo(String value) {
            addCriterion("`sosContactName1` >=", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1LessThan(String value) {
            addCriterion("`sosContactName1` <", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1LessThanOrEqualTo(String value) {
            addCriterion("`sosContactName1` <=", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1Like(String value) {
            addCriterion("`sosContactName1` like", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1NotLike(String value) {
            addCriterion("`sosContactName1` not like", value, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1In(List<String> values) {
            addCriterion("`sosContactName1` in", values, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1NotIn(List<String> values) {
            addCriterion("`sosContactName1` not in", values, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1Between(String value1, String value2) {
            addCriterion("`sosContactName1` between", value1, value2, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactName1NotBetween(String value1, String value2) {
            addCriterion("`sosContactName1` not between", value1, value2, "sosContactName1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1IsNull() {
            addCriterion("`sosContactRelation1` is null");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1IsNotNull() {
            addCriterion("`sosContactRelation1` is not null");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1EqualTo(Integer value) {
            addCriterion("`sosContactRelation1` =", value, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1NotEqualTo(Integer value) {
            addCriterion("`sosContactRelation1` <>", value, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1GreaterThan(Integer value) {
            addCriterion("`sosContactRelation1` >", value, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1GreaterThanOrEqualTo(Integer value) {
            addCriterion("`sosContactRelation1` >=", value, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1LessThan(Integer value) {
            addCriterion("`sosContactRelation1` <", value, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1LessThanOrEqualTo(Integer value) {
            addCriterion("`sosContactRelation1` <=", value, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1In(List<Integer> values) {
            addCriterion("`sosContactRelation1` in", values, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1NotIn(List<Integer> values) {
            addCriterion("`sosContactRelation1` not in", values, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1Between(Integer value1, Integer value2) {
            addCriterion("`sosContactRelation1` between", value1, value2, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactRelation1NotBetween(Integer value1, Integer value2) {
            addCriterion("`sosContactRelation1` not between", value1, value2, "sosContactRelation1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1IsNull() {
            addCriterion("`sosContactPhone1` is null");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1IsNotNull() {
            addCriterion("`sosContactPhone1` is not null");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1EqualTo(String value) {
            addCriterion("`sosContactPhone1` =", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1NotEqualTo(String value) {
            addCriterion("`sosContactPhone1` <>", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1GreaterThan(String value) {
            addCriterion("`sosContactPhone1` >", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1GreaterThanOrEqualTo(String value) {
            addCriterion("`sosContactPhone1` >=", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1LessThan(String value) {
            addCriterion("`sosContactPhone1` <", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1LessThanOrEqualTo(String value) {
            addCriterion("`sosContactPhone1` <=", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1Like(String value) {
            addCriterion("`sosContactPhone1` like", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1NotLike(String value) {
            addCriterion("`sosContactPhone1` not like", value, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1In(List<String> values) {
            addCriterion("`sosContactPhone1` in", values, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1NotIn(List<String> values) {
            addCriterion("`sosContactPhone1` not in", values, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1Between(String value1, String value2) {
            addCriterion("`sosContactPhone1` between", value1, value2, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andSosContactPhone1NotBetween(String value1, String value2) {
            addCriterion("`sosContactPhone1` not between", value1, value2, "sosContactPhone1");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNull() {
            addCriterion("`lastLoginIp` is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIsNotNull() {
            addCriterion("`lastLoginIp` is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpEqualTo(String value) {
            addCriterion("`lastLoginIp` =", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotEqualTo(String value) {
            addCriterion("`lastLoginIp` <>", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThan(String value) {
            addCriterion("`lastLoginIp` >", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpGreaterThanOrEqualTo(String value) {
            addCriterion("`lastLoginIp` >=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThan(String value) {
            addCriterion("`lastLoginIp` <", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLessThanOrEqualTo(String value) {
            addCriterion("`lastLoginIp` <=", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpLike(String value) {
            addCriterion("`lastLoginIp` like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotLike(String value) {
            addCriterion("`lastLoginIp` not like", value, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpIn(List<String> values) {
            addCriterion("`lastLoginIp` in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotIn(List<String> values) {
            addCriterion("`lastLoginIp` not in", values, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpBetween(String value1, String value2) {
            addCriterion("`lastLoginIp` between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLastLoginIpNotBetween(String value1, String value2) {
            addCriterion("`lastLoginIp` not between", value1, value2, "lastLoginIp");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("`longitude` is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("`longitude` is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("`longitude` =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("`longitude` <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("`longitude` >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("`longitude` >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("`longitude` <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("`longitude` <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("`longitude` like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("`longitude` not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("`longitude` in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("`longitude` not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("`longitude` between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("`longitude` not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("`latitude` is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("`latitude` is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("`latitude` =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("`latitude` <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("`latitude` >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("`latitude` >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("`latitude` <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("`latitude` <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("`latitude` like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("`latitude` not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("`latitude` in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("`latitude` not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("`latitude` between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("`latitude` not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andGpsAddressIsNull() {
            addCriterion("`gpsAddress` is null");
            return (Criteria) this;
        }

        public Criteria andGpsAddressIsNotNull() {
            addCriterion("`gpsAddress` is not null");
            return (Criteria) this;
        }

        public Criteria andGpsAddressEqualTo(String value) {
            addCriterion("`gpsAddress` =", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressNotEqualTo(String value) {
            addCriterion("`gpsAddress` <>", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressGreaterThan(String value) {
            addCriterion("`gpsAddress` >", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressGreaterThanOrEqualTo(String value) {
            addCriterion("`gpsAddress` >=", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressLessThan(String value) {
            addCriterion("`gpsAddress` <", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressLessThanOrEqualTo(String value) {
            addCriterion("`gpsAddress` <=", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressLike(String value) {
            addCriterion("`gpsAddress` like", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressNotLike(String value) {
            addCriterion("`gpsAddress` not like", value, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressIn(List<String> values) {
            addCriterion("`gpsAddress` in", values, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressNotIn(List<String> values) {
            addCriterion("`gpsAddress` not in", values, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressBetween(String value1, String value2) {
            addCriterion("`gpsAddress` between", value1, value2, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andGpsAddressNotBetween(String value1, String value2) {
            addCriterion("`gpsAddress` not between", value1, value2, "gpsAddress");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionIsNull() {
            addCriterion("`regAppVersion` is null");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionIsNotNull() {
            addCriterion("`regAppVersion` is not null");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionEqualTo(String value) {
            addCriterion("`regAppVersion` =", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionNotEqualTo(String value) {
            addCriterion("`regAppVersion` <>", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionGreaterThan(String value) {
            addCriterion("`regAppVersion` >", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionGreaterThanOrEqualTo(String value) {
            addCriterion("`regAppVersion` >=", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionLessThan(String value) {
            addCriterion("`regAppVersion` <", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionLessThanOrEqualTo(String value) {
            addCriterion("`regAppVersion` <=", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionLike(String value) {
            addCriterion("`regAppVersion` like", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionNotLike(String value) {
            addCriterion("`regAppVersion` not like", value, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionIn(List<String> values) {
            addCriterion("`regAppVersion` in", values, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionNotIn(List<String> values) {
            addCriterion("`regAppVersion` not in", values, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionBetween(String value1, String value2) {
            addCriterion("`regAppVersion` between", value1, value2, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegAppVersionNotBetween(String value1, String value2) {
            addCriterion("`regAppVersion` not between", value1, value2, "regAppVersion");
            return (Criteria) this;
        }

        public Criteria andRegFromIsNull() {
            addCriterion("`regFrom` is null");
            return (Criteria) this;
        }

        public Criteria andRegFromIsNotNull() {
            addCriterion("`regFrom` is not null");
            return (Criteria) this;
        }

        public Criteria andRegFromEqualTo(String value) {
            addCriterion("`regFrom` =", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromNotEqualTo(String value) {
            addCriterion("`regFrom` <>", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromGreaterThan(String value) {
            addCriterion("`regFrom` >", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromGreaterThanOrEqualTo(String value) {
            addCriterion("`regFrom` >=", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromLessThan(String value) {
            addCriterion("`regFrom` <", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromLessThanOrEqualTo(String value) {
            addCriterion("`regFrom` <=", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromLike(String value) {
            addCriterion("`regFrom` like", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromNotLike(String value) {
            addCriterion("`regFrom` not like", value, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromIn(List<String> values) {
            addCriterion("`regFrom` in", values, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromNotIn(List<String> values) {
            addCriterion("`regFrom` not in", values, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromBetween(String value1, String value2) {
            addCriterion("`regFrom` between", value1, value2, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegFromNotBetween(String value1, String value2) {
            addCriterion("`regFrom` not between", value1, value2, "regFrom");
            return (Criteria) this;
        }

        public Criteria andRegIpIsNull() {
            addCriterion("`regIp` is null");
            return (Criteria) this;
        }

        public Criteria andRegIpIsNotNull() {
            addCriterion("`regIp` is not null");
            return (Criteria) this;
        }

        public Criteria andRegIpEqualTo(String value) {
            addCriterion("`regIp` =", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpNotEqualTo(String value) {
            addCriterion("`regIp` <>", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpGreaterThan(String value) {
            addCriterion("`regIp` >", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpGreaterThanOrEqualTo(String value) {
            addCriterion("`regIp` >=", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpLessThan(String value) {
            addCriterion("`regIp` <", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpLessThanOrEqualTo(String value) {
            addCriterion("`regIp` <=", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpLike(String value) {
            addCriterion("`regIp` like", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpNotLike(String value) {
            addCriterion("`regIp` not like", value, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpIn(List<String> values) {
            addCriterion("`regIp` in", values, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpNotIn(List<String> values) {
            addCriterion("`regIp` not in", values, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpBetween(String value1, String value2) {
            addCriterion("`regIp` between", value1, value2, "regIp");
            return (Criteria) this;
        }

        public Criteria andRegIpNotBetween(String value1, String value2) {
            addCriterion("`regIp` not between", value1, value2, "regIp");
            return (Criteria) this;
        }

        public Criteria andBankCardIsNull() {
            addCriterion("`bankCard` is null");
            return (Criteria) this;
        }

        public Criteria andBankCardIsNotNull() {
            addCriterion("`bankCard` is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardEqualTo(String value) {
            addCriterion("`bankCard` =", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotEqualTo(String value) {
            addCriterion("`bankCard` <>", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardGreaterThan(String value) {
            addCriterion("`bankCard` >", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardGreaterThanOrEqualTo(String value) {
            addCriterion("`bankCard` >=", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardLessThan(String value) {
            addCriterion("`bankCard` <", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardLessThanOrEqualTo(String value) {
            addCriterion("`bankCard` <=", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardLike(String value) {
            addCriterion("`bankCard` like", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotLike(String value) {
            addCriterion("`bankCard` not like", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardIn(List<String> values) {
            addCriterion("`bankCard` in", values, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotIn(List<String> values) {
            addCriterion("`bankCard` not in", values, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardBetween(String value1, String value2) {
            addCriterion("`bankCard` between", value1, value2, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankCardNotBetween(String value1, String value2) {
            addCriterion("`bankCard` not between", value1, value2, "bankCard");
            return (Criteria) this;
        }

        public Criteria andBankMobileIsNull() {
            addCriterion("`bankMobile` is null");
            return (Criteria) this;
        }

        public Criteria andBankMobileIsNotNull() {
            addCriterion("`bankMobile` is not null");
            return (Criteria) this;
        }

        public Criteria andBankMobileEqualTo(String value) {
            addCriterion("`bankMobile` =", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileNotEqualTo(String value) {
            addCriterion("`bankMobile` <>", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileGreaterThan(String value) {
            addCriterion("`bankMobile` >", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileGreaterThanOrEqualTo(String value) {
            addCriterion("`bankMobile` >=", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileLessThan(String value) {
            addCriterion("`bankMobile` <", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileLessThanOrEqualTo(String value) {
            addCriterion("`bankMobile` <=", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileLike(String value) {
            addCriterion("`bankMobile` like", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileNotLike(String value) {
            addCriterion("`bankMobile` not like", value, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileIn(List<String> values) {
            addCriterion("`bankMobile` in", values, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileNotIn(List<String> values) {
            addCriterion("`bankMobile` not in", values, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileBetween(String value1, String value2) {
            addCriterion("`bankMobile` between", value1, value2, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andBankMobileNotBetween(String value1, String value2) {
            addCriterion("`bankMobile` not between", value1, value2, "bankMobile");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`createTime` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`createTime` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`createTime` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`createTime` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`createTime` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`createTime` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`createTime` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`createTime` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`createTime` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`createTime` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`createTime` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`createTime` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("`applyId` is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("`applyId` is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(String value) {
            addCriterion("`applyId` =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(String value) {
            addCriterion("`applyId` <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(String value) {
            addCriterion("`applyId` >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(String value) {
            addCriterion("`applyId` >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(String value) {
            addCriterion("`applyId` <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(String value) {
            addCriterion("`applyId` <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLike(String value) {
            addCriterion("`applyId` like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotLike(String value) {
            addCriterion("`applyId` not like", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<String> values) {
            addCriterion("`applyId` in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<String> values) {
            addCriterion("`applyId` not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(String value1, String value2) {
            addCriterion("`applyId` between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(String value1, String value2) {
            addCriterion("`applyId` not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`updateTime` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`updateTime` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`updateTime` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`updateTime` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`updateTime` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`updateTime` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`updateTime` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`updateTime` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`updateTime` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`updateTime` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`updateTime` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`updateTime` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("`bankName` is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("`bankName` is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("`bankName` =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("`bankName` <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("`bankName` >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("`bankName` >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("`bankName` <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("`bankName` <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("`bankName` like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("`bankName` not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("`bankName` in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("`bankName` not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("`bankName` between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("`bankName` not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("`productId` is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("`productId` is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("`productId` =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("`productId` <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("`productId` >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("`productId` >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("`productId` <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("`productId` <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("`productId` like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("`productId` not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("`productId` in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("`productId` not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("`productId` between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("`productId` not between", value1, value2, "productId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 21 16:25:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certificationUserInfo
     *
     * @mbg.generated Wed Nov 21 16:25:24 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}