package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CertificationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public CertificationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("`userId` is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("`userId` is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("`userId` =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("`userId` <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("`userId` >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("`userId` >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("`userId` <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("`userId` <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("`userId` like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("`userId` not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("`userId` in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("`userId` not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("`userId` between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("`userId` not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeIsNull() {
            addCriterion("`certificationType` is null");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeIsNotNull() {
            addCriterion("`certificationType` is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeEqualTo(String value) {
            addCriterion("`certificationType` =", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeNotEqualTo(String value) {
            addCriterion("`certificationType` <>", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeGreaterThan(String value) {
            addCriterion("`certificationType` >", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeGreaterThanOrEqualTo(String value) {
            addCriterion("`certificationType` >=", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeLessThan(String value) {
            addCriterion("`certificationType` <", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeLessThanOrEqualTo(String value) {
            addCriterion("`certificationType` <=", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeLike(String value) {
            addCriterion("`certificationType` like", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeNotLike(String value) {
            addCriterion("`certificationType` not like", value, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeIn(List<String> values) {
            addCriterion("`certificationType` in", values, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeNotIn(List<String> values) {
            addCriterion("`certificationType` not in", values, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeBetween(String value1, String value2) {
            addCriterion("`certificationType` between", value1, value2, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationtypeNotBetween(String value1, String value2) {
            addCriterion("`certificationType` not between", value1, value2, "certificationtype");
            return (Criteria) this;
        }

        public Criteria andCertificationitemIsNull() {
            addCriterion("`certificationItem` is null");
            return (Criteria) this;
        }

        public Criteria andCertificationitemIsNotNull() {
            addCriterion("`certificationItem` is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationitemEqualTo(String value) {
            addCriterion("`certificationItem` =", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemNotEqualTo(String value) {
            addCriterion("`certificationItem` <>", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemGreaterThan(String value) {
            addCriterion("`certificationItem` >", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemGreaterThanOrEqualTo(String value) {
            addCriterion("`certificationItem` >=", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemLessThan(String value) {
            addCriterion("`certificationItem` <", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemLessThanOrEqualTo(String value) {
            addCriterion("`certificationItem` <=", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemLike(String value) {
            addCriterion("`certificationItem` like", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemNotLike(String value) {
            addCriterion("`certificationItem` not like", value, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemIn(List<String> values) {
            addCriterion("`certificationItem` in", values, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemNotIn(List<String> values) {
            addCriterion("`certificationItem` not in", values, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemBetween(String value1, String value2) {
            addCriterion("`certificationItem` between", value1, value2, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationitemNotBetween(String value1, String value2) {
            addCriterion("`certificationItem` not between", value1, value2, "certificationitem");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitIsNull() {
            addCriterion("`certificationLimit` is null");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitIsNotNull() {
            addCriterion("`certificationLimit` is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitEqualTo(Date value) {
            addCriterion("`certificationLimit` =", value, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitNotEqualTo(Date value) {
            addCriterion("`certificationLimit` <>", value, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitGreaterThan(Date value) {
            addCriterion("`certificationLimit` >", value, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitGreaterThanOrEqualTo(Date value) {
            addCriterion("`certificationLimit` >=", value, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitLessThan(Date value) {
            addCriterion("`certificationLimit` <", value, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitLessThanOrEqualTo(Date value) {
            addCriterion("`certificationLimit` <=", value, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitIn(List<Date> values) {
            addCriterion("`certificationLimit` in", values, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitNotIn(List<Date> values) {
            addCriterion("`certificationLimit` not in", values, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitBetween(Date value1, Date value2) {
            addCriterion("`certificationLimit` between", value1, value2, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andCertificationlimitNotBetween(Date value1, Date value2) {
            addCriterion("`certificationLimit` not between", value1, value2, "certificationlimit");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("`flag` is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("`flag` is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("`flag` =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("`flag` <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("`flag` >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`flag` >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("`flag` <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("`flag` <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("`flag` in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("`flag` not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("`flag` between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("`flag` not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreattimeIsNull() {
            addCriterion("`creatTime` is null");
            return (Criteria) this;
        }

        public Criteria andCreattimeIsNotNull() {
            addCriterion("`creatTime` is not null");
            return (Criteria) this;
        }

        public Criteria andCreattimeEqualTo(Date value) {
            addCriterion("`creatTime` =", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeNotEqualTo(Date value) {
            addCriterion("`creatTime` <>", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeGreaterThan(Date value) {
            addCriterion("`creatTime` >", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`creatTime` >=", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeLessThan(Date value) {
            addCriterion("`creatTime` <", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeLessThanOrEqualTo(Date value) {
            addCriterion("`creatTime` <=", value, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeIn(List<Date> values) {
            addCriterion("`creatTime` in", values, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeNotIn(List<Date> values) {
            addCriterion("`creatTime` not in", values, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeBetween(Date value1, Date value2) {
            addCriterion("`creatTime` between", value1, value2, "creattime");
            return (Criteria) this;
        }

        public Criteria andCreattimeNotBetween(Date value1, Date value2) {
            addCriterion("`creatTime` not between", value1, value2, "creattime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certification
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 06 15:00:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 06 15:00:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}