package com.zdd.risk.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CertificationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public CertificationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("`userId` is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("`userId` is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("`userId` =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("`userId` <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("`userId` >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`userId` >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("`userId` <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("`userId` <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("`userId` like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("`userId` not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("`userId` in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("`userId` not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("`userId` between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("`userId` not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("`idCard` is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("`idCard` is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("`idCard` =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("`idCard` <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("`idCard` >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("`idCard` >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("`idCard` <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("`idCard` <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("`idCard` like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("`idCard` not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("`idCard` in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("`idCard` not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("`idCard` between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("`idCard` not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("`mobile` is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("`mobile` is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("`mobile` =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("`mobile` <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("`mobile` >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("`mobile` >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("`mobile` <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("`mobile` <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("`mobile` like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("`mobile` not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("`mobile` in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("`mobile` not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("`mobile` between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("`mobile` not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeIsNull() {
            addCriterion("`certificationType` is null");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeIsNotNull() {
            addCriterion("`certificationType` is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeEqualTo(String value) {
            addCriterion("`certificationType` =", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotEqualTo(String value) {
            addCriterion("`certificationType` <>", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeGreaterThan(String value) {
            addCriterion("`certificationType` >", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`certificationType` >=", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeLessThan(String value) {
            addCriterion("`certificationType` <", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeLessThanOrEqualTo(String value) {
            addCriterion("`certificationType` <=", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeLike(String value) {
            addCriterion("`certificationType` like", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotLike(String value) {
            addCriterion("`certificationType` not like", value, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeIn(List<String> values) {
            addCriterion("`certificationType` in", values, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotIn(List<String> values) {
            addCriterion("`certificationType` not in", values, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeBetween(String value1, String value2) {
            addCriterion("`certificationType` between", value1, value2, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationTypeNotBetween(String value1, String value2) {
            addCriterion("`certificationType` not between", value1, value2, "certificationType");
            return (Criteria) this;
        }

        public Criteria andCertificationItemIsNull() {
            addCriterion("`certificationItem` is null");
            return (Criteria) this;
        }

        public Criteria andCertificationItemIsNotNull() {
            addCriterion("`certificationItem` is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationItemEqualTo(String value) {
            addCriterion("`certificationItem` =", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemNotEqualTo(String value) {
            addCriterion("`certificationItem` <>", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemGreaterThan(String value) {
            addCriterion("`certificationItem` >", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemGreaterThanOrEqualTo(String value) {
            addCriterion("`certificationItem` >=", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemLessThan(String value) {
            addCriterion("`certificationItem` <", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemLessThanOrEqualTo(String value) {
            addCriterion("`certificationItem` <=", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemLike(String value) {
            addCriterion("`certificationItem` like", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemNotLike(String value) {
            addCriterion("`certificationItem` not like", value, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemIn(List<String> values) {
            addCriterion("`certificationItem` in", values, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemNotIn(List<String> values) {
            addCriterion("`certificationItem` not in", values, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemBetween(String value1, String value2) {
            addCriterion("`certificationItem` between", value1, value2, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationItemNotBetween(String value1, String value2) {
            addCriterion("`certificationItem` not between", value1, value2, "certificationItem");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitIsNull() {
            addCriterion("`certificationLimit` is null");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitIsNotNull() {
            addCriterion("`certificationLimit` is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitEqualTo(Date value) {
            addCriterion("`certificationLimit` =", value, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitNotEqualTo(Date value) {
            addCriterion("`certificationLimit` <>", value, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitGreaterThan(Date value) {
            addCriterion("`certificationLimit` >", value, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitGreaterThanOrEqualTo(Date value) {
            addCriterion("`certificationLimit` >=", value, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitLessThan(Date value) {
            addCriterion("`certificationLimit` <", value, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitLessThanOrEqualTo(Date value) {
            addCriterion("`certificationLimit` <=", value, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitIn(List<Date> values) {
            addCriterion("`certificationLimit` in", values, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitNotIn(List<Date> values) {
            addCriterion("`certificationLimit` not in", values, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitBetween(Date value1, Date value2) {
            addCriterion("`certificationLimit` between", value1, value2, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andCertificationLimitNotBetween(Date value1, Date value2) {
            addCriterion("`certificationLimit` not between", value1, value2, "certificationLimit");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("`flag` is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("`flag` is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("`flag` =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("`flag` <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("`flag` >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("`flag` >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("`flag` <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("`flag` <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("`flag` in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("`flag` not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("`flag` between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("`flag` not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("`remark` is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("`remark` is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("`remark` =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("`remark` <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("`remark` >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("`remark` >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("`remark` <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("`remark` <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("`remark` like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("`remark` not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("`remark` in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("`remark` not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("`remark` between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("`remark` not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("`creatTime` is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("`creatTime` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("`creatTime` =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("`creatTime` <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("`creatTime` >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`creatTime` >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("`creatTime` <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("`creatTime` <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("`creatTime` in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("`creatTime` not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("`creatTime` between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("`creatTime` not between", value1, value2, "creatTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certification
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 20 12:09:52 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table risk_certification
     *
     * @mbg.generated Tue Nov 20 12:09:52 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}