package com.zdd.risk.dao;

import com.zdd.risk.bean.ApproveResult;
import com.zdd.risk.bean.ApproveResultExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IApproveResultDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    long countByExample(ApproveResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int insert(ApproveResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int insertSelective(ApproveResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    List<ApproveResult> selectByExample(ApproveResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    ApproveResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") ApproveResult record, @Param("example") ApproveResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int updateByExample(@Param("record") ApproveResult record, @Param("example") ApproveResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int updateByPrimaryKeySelective(ApproveResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table risk_approveResult
     *
     * @mbg.generated Tue Nov 06 15:01:16 CST 2018
     */
    int updateByPrimaryKey(ApproveResult record);
}